# Generated by Django 4.2.2 on 2023-06-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_farmacia', '0002_alter_articulos_imagen_alter_envio_fecha_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulos',
            options={'verbose_name': 'Articulo', 'verbose_name_plural': 'Articulos'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='detalleingreso',
            options={'verbose_name': 'Detalle_Ingreso', 'verbose_name_plural': 'DetallesdeIngresos'},
        ),
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'verbose_name': 'detalle_venta', 'verbose_name_plural': 'detalles_ventas'},
        ),
        migrations.AlterModelOptions(
            name='envio',
            options={'verbose_name': 'envio', 'verbose_name_plural': 'envios'},
        ),
        migrations.AlterModelOptions(
            name='estados',
            options={'verbose_name': 'estado', 'verbose_name_plural': 'estados'},
        ),
        migrations.AlterModelOptions(
            name='ingreso',
            options={'verbose_name': 'Ingreso', 'verbose_name_plural': 'ingresos'},
        ),
        migrations.AlterModelOptions(
            name='orden',
            options={'verbose_name': 'Orden', 'verbose_name_plural': 'Ordenes'},
        ),
        migrations.AlterModelOptions(
            name='proveedores',
            options={'verbose_name': 'proveedor', 'verbose_name_plural': 'proveedores'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'rol', 'verbose_name_plural': 'roles'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.AlterModelTable(
            name='articulos',
            table='Articulos',
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='Categoria',
        ),
        migrations.AlterModelTable(
            name='detalleingreso',
            table='DetalleIngresos',
        ),
        migrations.AlterModelTable(
            name='detalleventa',
            table='DetallesVenta',
        ),
        migrations.AlterModelTable(
            name='envio',
            table='Envio',
        ),
        migrations.AlterModelTable(
            name='estados',
            table='Estados',
        ),
        migrations.AlterModelTable(
            name='ingreso',
            table='Ingresos',
        ),
        migrations.AlterModelTable(
            name='orden',
            table='Orden',
        ),
        migrations.AlterModelTable(
            name='proveedores',
            table='Proveedores',
        ),
        migrations.AlterModelTable(
            name='rol',
            table='Roles',
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table='Usuarios',
        ),
    ]
