# Generated by Django 4.2.2 on 2023-06-23 20:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('idarticulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('imagen', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='detalleingreso',
            fields=[
                ('iddetalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('preciounitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='estados',
            fields=[
                ('idestados', models.IntegerField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('idproveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipodni', models.CharField(max_length=10)),
                ('numerodni', models.IntegerField()),
                ('direccion', models.TextField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ROL',
            fields=[
                ('idrol', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(default='detalle', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='USUARIOS',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('tipo_dni', models.CharField(max_length=10)),
                ('numero_dni', models.IntegerField()),
                ('direccion', models.TextField(default='direccion', max_length=100)),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('contraseña', models.IntegerField()),
                ('idestados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_farmacia.estados')),
                ('idrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_farmacia.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('idorden', models.AutoField(primary_key=True, serialize=False)),
                ('tipoComprobante', models.CharField(max_length=20)),
                ('serieComprobante', models.CharField(max_length=10)),
                ('numeroComprobante', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_farmacia.estados')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_farmacia.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('idingreso', models.AutoField(primary_key=True, serialize=False)),
                ('tipoComprobante', models.CharField(max_length=20)),
                ('serieComprobante', models.CharField(max_length=10)),
                ('numeroComprobante', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_farmacia.estados')),
                ('idproveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_farmacia.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('idenvio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('direccion_envio', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cod_seguimiento', models.IntegerField(default=0)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_farmacia.estados')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_farmacia.orden')),
            ],
        ),
        migrations.CreateModel(
            name='detalleVenta',
            fields=[
                ('iddetalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_farmacia.articulos')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_farmacia.orden')),
            ],
        ),
        migrations.AddField(
            model_name='articulos',
            name='idcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_farmacia.categoria'),
        ),
    ]
