# Generated by Django 4.2.2 on 2023-06-24 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_farmacia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='imagen',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='envio',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
